#include QMK_KEYBOARD_H
#include "version.h"
#include "keymap_jp.h"

#define BASE 0 // default layer
#define LOWER 1 // symbols
#define RAISE 2 // media keys
#define ADJUST 3 // adjust

enum custom_keycodes {
#ifdef ORYX_CONFIGURATOR
  EPRM = EZ_SAFE_RANGE,
#else
  EPRM = SAFE_RANGE,
#endif
  VRSN,
  RGB_SLD
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* .---------------------------------------------. .---------------------------------------------.
 * |  ESC  |  1  |  2  |  3  |  4  |  5  |JP_CIRC| !JP_YEN |  6  |  7  |  8  |  9  |  0  | MINS  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |  Q  |  W  |  E  |  R  |  T  | LBRC  | ! RBRC  |  Y  |  U  |  I  |  O  |  P  | JP_AT |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | LCTL  |  A  |  S  |  D  |  F  |  G  |-------! !-------!  H  |  J  |  K  |  L  |SCLN |JP_COLO|
 * !-------+-----+-----+-----x-----x-----! LBRC  ! ! RBRC  !-----x-----x-----+-----+-----+-------!
 * | LSFT  |  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMM | DOT |SLSH |JP_BSLS|
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |LOWER |LGUI |LALT |JP_ZH|LOWER|                             !RAISE|HYPR |RALT |LBRC | RBRC |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               | LCTL  |JP_ZHTG| ! HYPR  | RALT  |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BSPC  !  DEL  | HOME  | ! PGUP  |  ENT  !  SPC  !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |  END  | ! PGDN  |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[BASE] = LAYOUT_ergodox(
  // left hand
  KC_ESC,    KC_1,      KC_2,      KC_3,      KC_4,      KC_5,      JP_CIRC,
  KC_TAB,    KC_Q,      KC_W,      KC_E,      KC_R,      KC_T,      KC_LBRC,
  KC_LCTL,   KC_A,      KC_S,      KC_D,      KC_F,      KC_G,
  KC_LSFT,   KC_Z,      KC_X,      KC_C,      KC_V,      KC_B,      KC_LBRC,
  MO(LOWER), KC_LGUI,   KC_LALT,   JP_ZHTG,   MO(LOWER),
                                                         KC_LCTL,   JP_ZHTG,
                                                                    KC_HOME,
                                              KC_SPC,   KC_BSPC,    KC_END,
  // right  hand      
  JP_YEN,    KC_6,      KC_7,      KC_8,      KC_9,      KC_0,      KC_MINS,
  KC_RBRC,   KC_Y,      KC_U,      KC_I,      KC_O,      KC_P,      JP_AT,
             KC_H,      KC_J,      KC_K,      KC_L,      KC_SCLN,   JP_COLN,
  KC_RBRC,   KC_N,      KC_M,      KC_COMM,   KC_DOT,    KC_SLSH,   JP_BSLS,
                        MO(RAISE), KC_HYPR,   KC_RALT,   KC_LBRC,   KC_RBRC,
  KC_HYPR,   KC_RALT,  
  KC_PGUP,
  KC_PGDN,   KC_DEL,    KC_ENT
),
/* .---------------------------------------------. .---------------------------------------------.
 * |       | F1  | F2  | F3  | F4  | F5  |       | !       | F6  | F7  | F8  | F9  | F10 |  F11  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       | BRK |     | INS |SLCK |PSCR |  F12  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |-------! !-------!LEFT |DOWN | UP  |RIGHT|     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !MO(AD|     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[LOWER] = LAYOUT_ergodox(
  // left hand
  _______,   KC_F1,     KC_F2,     KC_F3,     KC_F4,     KC_F5,     _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,
                                                         _______,   _______,
                                                                    _______,
                                              _______,   _______,   _______,
  // right hand
  _______,   KC_F6,     KC_F7,     KC_F8,     KC_F9,     KC_F10,    KC_F11,
  _______,   KC_BRK,    _______,   KC_INS,    KC_SLCK,   KC_PSCR,   KC_F12,
             KC_LEFT,   KC_DOWN,   KC_UP,     KC_RIGHT,  _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
                        MO(ADJUST),_______,   _______,   _______,   _______,
  _______,   _______,
  _______,
  _______,   _______,   _______
),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |MS_U |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |MS_L |MS_D |MS_R |     |-------! !-------!     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |MO(AD|                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BTN1  ! BTN2  |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[RAISE] = LAYOUT_ergodox(
  // left hand
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   KC_MS_U,   _______,   _______,   _______,
  _______,   _______,   KC_MS_L,   KC_MS_D,   KC_MS_R,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   MO(ADJUST),
                                                         _______,   _______,
                                                                    _______,
                                              KC_BTN1,   KC_BTN2,   _______,
  // right hand
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
             _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
                        _______,   _______,   _______,   _______,   _______,
  _______,   _______,
  _______,
  _______,   _______,   _______
),
/* .---------------------------------------------. .---------------------------------------------.
 * | VRSN  |     |     |     |     |     | RESET | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |-------! !-------!     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  | EPRM |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[ADJUST] = LAYOUT_ergodox(
  // left hand
  VRSN,      _______,   _______,   _______,   _______,   _______,   RESET,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  EPRM,      _______,   _______,   _______,   _______,
                                                         _______,   _______,
                                                                    _______,
                                              _______,   _______,   _______,
  // right hand
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
             _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
                        _______,   _______,   _______,   _______,   _______,
  _______,   _______,
  _______,
  _______,   _______,   _______
),
};

/*
  TEMPLATE

  // left hand
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,
                                                         _______,   _______,
                                                                    _______,
                                              _______,   _______,   _______,
  // right hand
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
             _______,   _______,   _______,   _______,   _______,   _______,
  _______,   _______,   _______,   _______,   _______,   _______,   _______,
                        _______,   _______,   _______,   _______,   _______,
  _______,   _______,
  _______,
  _______,   _______,   _______

*/

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  if (record->event.pressed) {
    switch (keycode) {
      case EPRM:
        eeconfig_init();
        return false;
      case VRSN:
        SEND_STRING (QMK_KEYBOARD "/" QMK_KEYMAP " @ " QMK_VERSION);
        return false;
      #ifdef RGBLIGHT_ENABLE
      case RGB_SLD:
        rgblight_mode(1);
        return false;
      #endif
    }
  }
  return true;
}

// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {
#ifdef RGBLIGHT_COLOR_LAYER_0
  rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
#endif
};

// Runs whenever there is a layer state change.
layer_state_t layer_state_set_user(layer_state_t state) {
  ergodox_board_led_off();
  ergodox_right_led_1_off();
  ergodox_right_led_2_off();
  ergodox_right_led_3_off();

  uint8_t layer = get_highest_layer(state);
  switch (layer) {
      case 0:
        #ifdef RGBLIGHT_COLOR_LAYER_0
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
        #else
        #ifdef RGBLIGHT_ENABLE
          rgblight_init();
        #endif
        #endif
        break;
      case 1:
        ergodox_right_led_1_on();
        #ifdef RGBLIGHT_COLOR_LAYER_1
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_1);
        #endif
        break;
      case 2:
        ergodox_right_led_2_on();
        #ifdef RGBLIGHT_COLOR_LAYER_2
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_2);
        #endif
        break;
      case 3:
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_3
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_3);
        #endif
        break;
      case 4:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        #ifdef RGBLIGHT_COLOR_LAYER_4
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_4);
        #endif
        break;
      case 5:
        ergodox_right_led_1_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_5
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_5);
        #endif
        break;
      case 6:
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_6
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_6);
        #endif
        break;
      case 7:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_7
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_7);
        #endif
        break;
      default:
        break;
    }

  return state;
};
